import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import * as textwrap from '../src/text/textwrap.mjs';
import * as shlex from '../src/text/shlex.mjs';
import * as difflib from '../src/difflib/index.mjs';
import * as urlparse from '../src/urlparse/index.mjs';

// Sample cases generated by CPython; every one must match. Add your own tests next to this file.
const { cases, python } = JSON.parse(readFileSync(new URL('./smoke-cases.json', import.meta.url), 'utf8'));
const modules = { textwrap, shlex, difflib, urlparse };

/** The comparable shape of a JS result for one case (Python tuples/named tuples are arrays in the cases). */
function shape(fn, value, expected) {
  if (fn === 'urlsplit' && Array.isArray(expected)) return [value.scheme, value.netloc, value.path, value.query, value.fragment];
  if (fn === 'urlparse') return [value.scheme, value.netloc, value.path, value.params, value.query, value.fragment];
  if (fn === 'urlsplit') return Object.fromEntries(['scheme', 'netloc', 'path', 'query', 'fragment', 'username', 'password', 'hostname', 'port'].map(key => [key, value[key] === undefined ? null : value[key]]));
  if (fn === 'urldefrag') return [value.url, value.fragment];
  return value;
}

function run(c) {
  const module = modules[c.module];
  if (c.fn.startsWith('SequenceMatcher.')) return new module.SequenceMatcher(...c.ctor)[c.fn.slice('SequenceMatcher.'.length)](...c.args);
  return module[c.fn](...c.args);
}

function check(c) {
  let actual;
  try { actual = run(c); } catch (error) {
    if (c.error) return error?.name === c.error ? undefined : `threw ${error?.name}: ${error?.message}, expected ${c.error}`;
    return `threw ${error?.name}: ${error?.message}`;
  }
  if (c.error) return `returned ${JSON.stringify(actual)}, expected ${c.error}`;
  const value = shape(c.fn, actual, c.value);
  if (typeof c.value === 'number' && !Number.isInteger(c.value)) return Math.abs(value - c.value) < 1e-12 ? undefined : `got ${value}, expected ${c.value}`;
  try { assert.deepStrictEqual(value, c.value); return undefined; } catch { return `got ${JSON.stringify(value)}, expected ${JSON.stringify(c.value)}`; }
}

for (const module of ['textwrap', 'shlex', 'difflib', 'urlparse']) {
  const mine = cases.filter(c => c.module === module);
  for (const fn of [...new Set(mine.map(c => c.fn))]) {
    test(`${module}.${fn} matches CPython ${python}`, () => {
      const failures = mine.filter(c => c.fn === fn).flatMap(c => { const problem = check(c); return problem ? [`${JSON.stringify(c.ctor ?? [])} ${JSON.stringify(c.args).slice(0, 300)}: ${problem.slice(0, 400)}`] : []; });
      assert.equal(failures.length, 0, `${failures.length} of ${mine.filter(c => c.fn === fn).length} cases differ:\n${failures.slice(0, 5).join('\n')}`);
    });
  }
}
