import { describe, expect, it } from "vitest";
import { delegationRules } from "../../src/extension/mode.js";

// Explicit expected prose, not derived from the implementation under test.
const REFERENCE = "Pass references, not copies: repository paths with line ranges or symbol names, reproduction commands, artifact and run-record paths. Paste only short decisive snippets a worker cannot reproduce (an exact error line or user-provided text); never whole files, diffs or long logs.";
const GIT = "Git: workers never commit or push on their own, and this session cannot run commits itself. Only when the user explicitly asked in this conversation to commit or push, pass `git` ({commit:true} or {push:true, remote?, branch?}) to an implement, game-asset or video orche_task; explore, answer and verify reject it. The grant covers that assignment only, so scope the commit to the task's files where possible (pass `files` and name the paths in `request`) and check the commits listed in the result before reporting.";
const HANDOFF = "Single hand-off (also auto's orche_task path): main analyses the user's intent, purpose and requirements. Write `request` as: Intent/Purpose; numbered requirements checklist R1..Rn as lines `R1: …`, each testable with acceptance criteria; Constraints and non-goals; Assumptions (explicit when there is no UI); and a final Original request section containing the user's ORIGINAL request text verbatim. Put relevant background and file/evidence references in `context`. One end-to-end assignment per round: implement for changes, answer for read-only questions. Do not split the task into explore/implement/verify phases, and never send an explore before an implement for the same request. Never end a turn without attempting the requested change because of its size or risk. The worker analyses requirements, creates a Task DAG with task_plan and executes nodes sequentially without main intervention while it runs. Standard roles inherit main's CURRENT model and thinking at hand-off and compact above 50% context, preserving requirements, original request and the assignment's plan. Specialists keep their routes and do not receive task_plan or 50% compaction.";
const REUSE = "Reuse: problems and user follow-ups go to the SAME worker (pass its id in `worker`). Review the result, its evidence and checklist, and run trusted project checks. Restate additional or corrected requirements in the same hand-off format with new R-ids or revised ones and repeat. When a requirement remains unmet or partial for 2 consecutive assignments of that worker, hand ONLY the unmet items to a NEW worker (omit worker), with their requirements, relevant file references and the previous worker's evidence; do not resend the whole task. Never claim a reuse that did not happen (unknown ids are errors; workers are gone after a reload).";
const SUPERVISION = "Supervision: a worker's report is not acceptance, and its checklist is a self-report: in benchmarks workers reported every item met while hidden acceptance tests still failed because they implemented a different reading of a requirement. Read the report and its key evidence, run the trusted project checks yourself, confirm for each requirement that the cited verifiedBy check asserts the acceptance as stated in the Original request, check every reported ambiguity's chosen reading against the user's original wording (send a correction to the same worker when it differs), and report unverified items as unverified. Send a separate verify assignment only when the user explicitly asks for independent verification; otherwise send problems to the same worker with what is wrong.";
export const EXPECTED_SINGLE_RULES = [
  "orche mode: single. You cannot edit files in this session: edit, write and ast_rewrite are disabled; explicit shell mutations and unverified shell syntax are blocked. You keep the conversation, requirements and acceptance, with limited inspection to state the task precisely and trusted project checks for acceptance. Do not explore or implement the codebase yourself; delegate with orche_task.",
  "orche_task (single): one persistent worker; available roles: explore | answer | implement | verify | game-asset | video. For this workflow choose implement for changes, answer for read-only questions. The worker owns the whole task end to end: investigate, implement completely, add or update tests, run relevant project checks and iterate until they pass, then report.",
  GIT,
  "Single workflow: refine the requirements with the user: goal, constraints and acceptance criteria. Inspect only what is needed to state the task precisely. Ask the user only about decisions you cannot reasonably make; without a UI, make a reasonable assumption and state it in the request and final report. Hand the whole task to ONE orche_task in ONE end-to-end assignment, even when it is large, multi-sized or risky: role implement for changes, answer for read-only questions. Do not split the task into explore/implement/verify phases, and never send an explore before an implement for the same request. Never stop to ask the user to switch modes in order to proceed, and never end a turn without attempting the requested change because of its size or risk. orche_run is disabled in mode single. Multi is optional advice only: mention it at most once, in the final report after the work is done (for example, 'orche_run could parallelize this; /orche mode auto or multi'), never as a reason to stop. This workflow is the same with and without a UI.",
  HANDOFF, REUSE, SUPERVISION, REFERENCE,
].join("\n");
export const EXPECTED_AUTO_RULES = [
  "orche mode: auto. You cannot edit files in this session: edit, write and ast_rewrite are disabled; explicit shell mutations and unverified shell syntax are blocked. You keep the conversation, inspection (read, grep, find, ls, ast_search, diagnostics, simple static Bash) and trusted project checks. Delegate changes through the single workflow with orche_task by default; use orche_run only under the strict multi criteria below:",
  "orche_task (single): one persistent worker; available roles: explore | answer | implement | verify | game-asset | video. For this workflow choose implement for changes, answer for read-only questions. The worker owns the whole task end to end. Use game-asset for game art/audio/model assets, and video for video production.",
  GIT,
  "orche_run (multi): coordinator, parallel workers and an independent verifier. Use ONLY when one of these holds: (a) the user explicitly asks for multi-agent orchestration or parallel workers; (b) the request contains at least two independent units with disjoint write sets, each substantial on its own, where parallel execution clearly shortens the work; (c) a defect's cause is unknown AND parallel competing hypotheses are clearly warranted. Otherwise, and whenever in doubt, use single through orche_task. Size, risk, user-visible behaviour and a desire for verification alone are not multi triggers.",
  HANDOFF, REUSE, SUPERVISION, REFERENCE,
  "After a failed orche_run, do not start another orche_run for the same request (even if multi criteria hold). Send remaining issues to handed-over workers via orche_task: implement for fixes, verify for re-checks; pass the reported id in `worker` to reuse context.",
  "orche runs do not see this conversation. Make `request` self-contained: the goal, the decisions made so far, the relevant files and findings from this conversation, constraints, and acceptance criteria (what must be true and how to check it). Put background that is not the instruction itself in `context`. " + REFERENCE + " When orche_run returns, report its result to the user; do not redo its work.",
].join("\n");

describe("explicit single/auto delegation rule snapshots", () => {
  it("single hand-off, DAG and checklist review loop", () => expect(delegationRules("single")).toBe(EXPECTED_SINGLE_RULES));
  it("auto strict multi criteria and in doubt -> single", () => expect(delegationRules("auto")).toBe(EXPECTED_AUTO_RULES));
  it("auto defaults changes to single, mentions in-doubt once and never phase-splits or stops for size/risk", () => {
    const rules = delegationRules("auto");
    expect(rules).toContain("Delegate changes through the single workflow with orche_task by default");
    expect(rules).not.toContain("every multi-file investigation");
    expect(rules.match(/whenever in doubt/g)).toHaveLength(1);
    expect(rules).toContain("Do not split the task into explore/implement/verify phases");
    expect(rules).toContain("Never end a turn without attempting the requested change because of its size or risk");
    expect(rules).toContain("as lines `R1: …`");
  });
});
